In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [20]:
wine = pd.read_csv('C:/Users/Akshay/Desktop/wine.csv')

In [21]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [22]:
wine.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
x = wine.drop("quality", axis=1)
y = wine["quality"]

In [5]:
x = pd.DataFrame(x)
y = pd.DataFrame(y)

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size = 0.3, random_state=18)

In [7]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

In [8]:
model.fit(x_train,y_train)

C:\Users\Akshay\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
model.predict(x_test)

array([5, 5, 5, 5, 7, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 6, 5, 7, 6, 5, 5, 6, 5, 5, 5, 6, 6, 7, 6, 7, 6, 6, 5, 5, 5,
       5, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 7, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5,
       7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 7, 5, 7, 5, 5, 5, 6, 5, 5, 5,
       6, 5, 5, 5, 5, 6, 5, 6, 7, 7, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5,
       5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 7, 6, 6, 6, 5, 6, 5,
       6, 5, 5, 5, 7, 6, 5, 5, 6, 5, 7, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5,
       6, 5, 7, 5, 7, 5, 6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 7, 6, 5, 5, 5, 5,
       5, 5, 7, 5, 5, 6, 5, 6, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5,
       5, 3, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 7, 5, 7,
       6, 6, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 7, 5, 5, 7, 6, 6, 6, 6, 5, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5,
       5, 7, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5,
       6, 7, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6,

In [10]:
model.score(x_test,y_test)

0.69375

In [11]:
from sklearn.tree import DecisionTreeClassifier  
model1=DecisionTreeClassifier()  

In [12]:
model1.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [13]:
model1.predict(x_test)

array([6, 5, 6, 5, 7, 6, 5, 5, 5, 7, 6, 5, 6, 6, 7, 5, 6, 6, 5, 6, 6, 5,
       6, 6, 7, 5, 7, 6, 6, 6, 6, 5, 5, 5, 6, 6, 7, 5, 7, 6, 6, 5, 6, 5,
       5, 5, 7, 6, 7, 6, 5, 5, 6, 5, 6, 7, 5, 8, 5, 6, 5, 5, 7, 7, 6, 5,
       7, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 7, 5, 5, 7, 6, 6, 5, 6, 5, 5, 6,
       6, 6, 5, 5, 5, 6, 5, 6, 7, 7, 6, 6, 5, 6, 5, 7, 5, 6, 5, 5, 5, 5,
       6, 5, 6, 6, 6, 7, 7, 6, 6, 7, 6, 5, 6, 6, 5, 7, 5, 6, 6, 5, 6, 6,
       8, 5, 5, 5, 7, 6, 5, 6, 6, 6, 7, 5, 6, 6, 5, 4, 6, 5, 5, 6, 6, 5,
       7, 5, 7, 5, 6, 5, 5, 5, 6, 6, 6, 7, 5, 6, 6, 5, 7, 6, 8, 5, 5, 5,
       6, 5, 7, 5, 5, 6, 4, 6, 5, 7, 5, 7, 4, 6, 5, 6, 6, 6, 6, 5, 7, 7,
       5, 3, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 5, 7,
       6, 6, 6, 5, 6, 7, 5, 5, 6, 7, 6, 4, 7, 6, 5, 6, 6, 6, 5, 6, 5, 5,
       5, 5, 5, 6, 6, 7, 7, 5, 5, 6, 5, 4, 6, 6, 6, 5, 4, 6, 7, 6, 5, 5,
       5, 7, 6, 6, 5, 5, 6, 5, 5, 6, 7, 6, 5, 5, 6, 6, 6, 7, 5, 4, 5, 5,
       5, 7, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6,

In [14]:
model1.score(x_test,y_test)

0.625

In [15]:
from sklearn.neighbors import KNeighborsClassifier
model2=KNeighborsClassifier() 

In [16]:
model2.fit(x_train, y_train)

C:\Users\Akshay\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
model2.predict(x_test)

array([5, 5, 6, 6, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 7, 6, 5, 5, 5, 5, 5, 6, 5, 5,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 7, 5, 7, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6,
       5, 6, 6, 5, 5, 7, 5, 5, 5, 5, 5, 7, 6, 5, 8, 5, 5, 6, 6, 5, 5, 5,
       6, 5, 5, 6, 6, 6, 5, 3, 6, 7, 6, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 5,
       7, 5, 5, 4, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 5, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 7, 5, 7, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 7, 5, 5, 5, 6, 5,
       5, 7, 7, 5, 6, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 6, 7, 7, 5, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 4, 6, 6, 7, 6, 5,
       5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 7, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5,
       6, 7, 5, 5, 5, 6, 7, 6, 5, 5, 5, 5, 3, 5, 6,

In [18]:
model2.score(x_test, y_test)

0.5083333333333333